sonar.projectKey=aws-terraform-github-actions
sonar.projectName=AWS Terraform GitHub Actions
sonar.sources=microservices/api-service/src,microservices/message-service/src,microservices/frontend/public,microservices/frontend/admin
sonar.tests=microservices/api-service/test,microservices/message-service/test
